from pydantic import BaseModel
from typing import Optional
from datetime import datetime  # 导入 datetime

class FuelCellData(BaseModel):
    id: int
    time: datetime
    status: str
    air_flow: float
    air_temperature: float
    water_pressure: float
    stack_current: Optional[float] = None  # 允许为 None
    stack_voltage: Optional[float] = None  # 允许为 None
    real_power: float
    stack_outlet_water_temperature: float
    stack_inlet_water_temperature: float
    hydrogen_pressure: float
    air_pressure: float
    max_single_voltage: float
    min_single_voltage: float
    avg_single_voltage: float
    start_stop_control: str
    control_mode_selection: str
    target_current: float
    dcdc_hotspot_temperature: float
    dcdc_status: str
    fault_info: str
    output_voltage: float
    output_current: float
    input_voltage: float
    input_current: float
    hydrogen_concentration: float
    insulation_resistance: float
    single_voltage1: float
    single_voltage2: float
    single_voltage3: float
    single_voltage4: float
    single_voltage5: float
    single_voltage6: float
    single_voltage7: float
    single_voltage8: float
    single_voltage9: float
    single_voltage10: float
    single_voltage11: float
    single_voltage12: float
    single_voltage13: float
    single_voltage14: float
    single_voltage15: float
    single_voltage16: float
    single_voltage17: float
    single_voltage18: float
    single_voltage19: float
    single_voltage20: float
    single_voltage21: float
    single_voltage22: float
    single_voltage23: float
    single_voltage_low: int
    module_hydrogen_concentration_abnormal: int
    inlet_outlet_temperature_difference_abnormal: int
    outlet_water_temperature_high_abnormal: int
    water_pump_fault: int
    hydrogen_pump_abnormal: int
    hydrogen_pressure_high_abnormal: int
    hydrogen_export_pressure_sensor_abnormal: int
    dc_communication_abnormal: int
    dcdc_fault: int
    heater_fault: int
    hydrogen_tank_temperature_abnormal: int
    hydrogen_tank_high_pressure_abnormal: int
    hydrogen_tank_medium_pressure_abnormal: int
    hydrogen_tank_low_pressure_abnormal: int
    fcu_communication_abnormal: int
    temperature_sensor_abnormal: int
    hydrogen_pressure_sensor_self_check_abnormal: int
    hydrogen_tank_soc_low: int
    hydrogen_export_pressure_low_abnormal: int
    air_pressure_low_abnormal: int
    air_pressure_high_abnormal: int
    air_temperature_high_abnormal: int
    cooling_water_pressure_high_abnormal: int
    single_voltage_high_abnormal: int
    insulation_low_abnormal: int
    hydrogen_air_pressure_difference_large_abnormal_negative: int
    hydrogen_air_pressure_difference_large_abnormal_positive: int
    start_hydrogen_pressure_low_below_20kpa: int
    hydrogen_leak_check_failure: int
    total_voltage: float
    total_current: float
    remaining_capacity: float
    nominal_capacity: float
    cycle_count: int
    remaining_capacity_percentage: float
    production_date: str
    range: float
    software_version: str
    speed: int
    vehicle_speed: float
